version: "3"

services:
  plex:
    image: linuxserver/plex
    environment:
      - env_var_name=${VARIABLE_NAME} # here it is
      - env_var_name2=${OTHER_VARIABLE_NAME} # here it is
      - env_var_name3=${TEST} # here it is
      - env_var_name4=${test} # here it is
      - env_var_name5=${test2} # here it is